services:
  web-app:
    image: php:apache
      # to sync whatever is in your local to your docker image
    volumes:
      - "./app:/var/www/html"
    ports:
      - "80:80"
  db:
    image: mysql:latest
    environment:
        - MYSQL_HOST=mysql
        - MYSQL_USER=php_docker
        - MYSQL_PASSWORD=password
        - MYSQL_ALLOW_EMPTY_PASSWORD=1
        - MYSQL_DATABASE=mystore
    # this is how we persist a sql db even when container stops
    volumes:
      - "./db:/docker-entrypoint-initdb.d" 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306